name: rapi2
description: An awesome delivery app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-49.0.dev <4.0.0'

dependencies:
# Core dependencies
  equatable: ^2.0.5
  meta: ^1.9.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  kt_dart: ^1.1.0
  recase: ^4.1.0

# Injection dependencies  
  injectable: ^2.1.2
  get_it: ^7.6.0

# Storage dependencies
  get_storage: ^2.1.1
  image_picker: ^0.8.9
  path_provider: ^2.0.15


# Bloc dependencies
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1


# Network dependencies
  dio: ^5.1.2
  connectivity_plus: ^4.0.1

# Location dependencies
  geolocator: ^9.0.2

# Test dependencies
  mockito: ^5.4.1
  bloc_test: ^9.1.3  
  stack_trace: ^1.11.0
  logging: ^1.0.0


# Flutter dependencies
  flutter:
    sdk: flutter

# Cupertino icons    
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.4
  build_runner: ^2.4.5
  json_serializable: ^6.6.2
  injectable_generator: ^2.1.6


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  
  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Regular.ttf
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist-SemiBold.ttf
          weight: 600
